title: Capricorn Jekyll Theme
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/capricorn-jekyll-theme"
url: "https://nrdybhu1.github.io"
twitter_username: jekyllrb
github_username:  Jekyll

favicon: favicon.ico

collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    image: ""
future: true

show_excerpts: true

plugins:
 - jekyll-avatar
 - jekyll-feed
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jemoji

feed:
  categories:
   - tutorial
   - blog

strict_front_matter: true

exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - _site/
 - README.md
